version: "3.8"

services:
  backend:
    image: employee-backend:1
    container_name: backend
    ports:
     - "5000:5000"

  frontend:
    image: employee_frontend:1
    container_name: frontend
    ports:
     - "80:80"   
    depends_on:
     -  backend